# Generated by Django 3.1 on 2020-09-05 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('careforyou', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childcare',
            name='quality_id',
        ),
        migrations.AddField(
            model_name='childcare',
            name='state',
            field=models.CharField(default=0, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='childcare',
            name='temp_closed',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='quality',
            name='childcare_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='careforyou.childcare'),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='childcare_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='careforyou.childcare'),
        ),
    ]
