# Generated by Django 3.1 on 2020-09-05 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('careforyou', '0002_auto_20200905_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childcare',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='childcare',
            name='fax',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='childcare',
            name='language_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careforyou.language'),
        ),
        migrations.AlterField(
            model_name='childcare',
            name='phone',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
