# Generated by Django 3.1 on 2020-09-05 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careforyou', '0004_auto_20200905_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='childcare',
            name='email',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
