# Generated by Django 3.1 on 2020-09-05 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('careforyou', '0006_auto_20200905_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childcare',
            name='language_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careforyou.language'),
        ),
        migrations.AlterField(
            model_name='childcare',
            name='program_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careforyou.program'),
        ),
    ]
